config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  root to: "home#index"

  resources :items
  resources :packages
  resources :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :package, optional: true
  belongs_to :lot
  belongs_to :customer, optional: true

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :lot_id, presence: true, uniqueness: true
  validates :weight, numericality: { greater_than: 0, allow_nil: true }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :service_fee, numericality: { greater_than_or_equal_to: 0, allow_nil: true }
  validates :internal_shipping_costs, numericality: { greater_than_or_equal_to: 0, allow_nil: true }
  validates :country_fee, numericality: { greater_than_or_equal_to: 0, allow_nil: true }
  validates :code, presence: true
end

app/models/lot.rb
class Lot < ApplicationRecord
  has_many :items
  belongs_to :package, optional: true

  validates :code, presence: true
end

app/models/package.rb
class Package < ApplicationRecord
  has_many :items
  has_many :lots

  validate :must_have_at_least_one_lot

  private

  def must_have_at_least_one_lot
    errors.add(:base, 'Package must have at least one lot') if lots.empty?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params.except(:lot_code))
    lot = Lot.new(code: item_params[:lot_code])

    unless lot.valid?
      lot.errors.full_messages.each do |msg|
        @item.errors.add(:lot_code, msg)
      end
    end

    lot.save!
    @item.lot = lot

    if @item.valid?
      @item.save!
      redirect_to items_path, notice: "Item was successfully created."
    else
      binding.pry
      flash.now[:alert] = "Errors: <br>".html_safe + @item.errors.full_messages.join("<br>").html_safe
      render :new, status: :unprocessable_entity
    end
  end

  def item_params
    params.require(:item).permit(:lot_code, :name, :weight, :price, :service_fee,
                                  :internal_shipping_costs, :country_fee
                                )
  end
end

app/controllers/lot_controller.rb
class LotController < ApplicationController
  def
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/lot_helper.rb
module LotHelper
end

app/helpers/package_helper.rb
module PackageHelper
end

app/views/customers/index.html.erb
<div class='container'>Customers</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<div class='container'>
  <h1>Welcome, this is the home page</h1>
  <button
    type="button"
    class="btn btn-lg btn-danger"
    data-bs-toggle="popover"
    title="Popover title"
    data-bs-content="Amazing content, right ?"
  >
    Click to toggle popover
  </button>
</div>

<div data-controller="hello">
  <input class='input' data-hello-target="name" type="text">
  <button data-action='click->hello#greet' class='btn btn-success'>Greet</button>
</div>

app/views/items/index.html.erb
<div class='container'>Items</div>

<%= link_to 'New item', new_item_path, class: 'btn btn-primary' %>

app/views/items/new.html.erb
<%# <div class="d-flex flex-row mb-3">
  <div class="p-2">
    <label for="exampleInputEmail1" class="form-label">Item Code</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="p-2">
    <label for="exampleInputEmail1" class="form-label">Item Code</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="p-2">
    <label for="exampleInputEmail1" class="form-label">Item Code</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="p-2">
    <label for="exampleInputEmail1" class="form-label">Item Code</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="p-2">
    <label for="exampleInputEmail1" class="form-label">Item Code</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="p-2">
    <label for="exampleInputEmail1" class="form-label">Item Code</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
</div> %>

<%# <form>
  <div class="d-flex flex-row mb-3">
    <div class="p-2">
      <label for="exampleInputEmail1" class="form-label">Item Code</label>
      <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="p-2">
      <label for="exampleInputEmail1" class="form-label">Item Code</label>
      <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="p-2">
      <label for="exampleInputEmail1" class="form-label">Item Code</label>
      <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="p-2">
      <label for="exampleInputEmail1" class="form-label">Item Code</label>
      <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="p-2">
      <label for="exampleInputEmail1" class="form-label">Item Code</label>
      <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="p-2">
      <label for="exampleInputEmail1" class="form-label">Item Code</label>
      <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form> %>


<%= render 'shared/items_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Crm" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "shared/navbar" %>
		<div class='container'>
      <%= render "shared/flash" %>
			<%= yield %>
		</div>
  </body>
</html>

app/views/shared/_flash.html.erb
<div class: "flash-messages-container", data: {controller: "flash"}>
	<% if notice %>
		<%= render "shared/flash/success" %>
	<% end %>
	<% if alert %>
		<%= render "/flash/danger" %>
	<% end %>
</div>

app/views/shared/_items_form.html.erb
<div class='container mt-4'>
  <%= form_with model: @item do |form| %>
    <div class="row mb-3"> <%# Оборачиваем все поля в .row %>
      <div class="col-md-3"> <%# col-md-2 для item_code (занимает 2 из 12 колонок) %>
        <div class="mb-3"> <%# Добавляем mb-3 внутри колонки для отступа снизу %>
          <%= form.label :item_code, class: 'form-label' %>
          <%= form.text_field :lot_code, class: 'form-control' %>
          <% if @item.errors[:lot_code].any? %>
            <div class="invalid-feedback d-block"> <%# d-block для отображения %>
              <%= @item.errors.full_messages_for(:lot_code).first %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-4"> <%# col-md-4 для name (занимает 4 из 12 колонок) - это будет ваше "длинное" поле %>
        <div class="mb-3">
          <%= form.label :name, class: 'form-label' %>
          <%= form.text_field :name, class: 'form-control', required: true, minlength: 3 %>
          <% if @item.errors[:name].any? %>
            <div class="invalid-feedback d-block"> <%# d-block для отображения %>
              <%= @item.errors.full_messages_for(:name).join(', ') %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-2"> <%# col-md-2 для weight %>
        <div class="mb-3">
          <%= form.label :weight, class: 'form-label' %>
          <%= form.number_field :weight, class: 'form-control', required: true %>
          <% if @item.errors[:weight].any? %>
            <div class="invalid-feedback d-block"> <%# d-block для отображения %>
              <%= @item.errors.full_messages_for(:weight).join(', ') %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-3"> <%# col-md-2 для price %>
        <div class="mb-3">
          <%= form.label :price, class: 'form-label' %>
          <%= form.text_field :price, class: 'form-control', required: true %>
          <% if @item.errors[:price].any? %>
            <div class="invalid-feedback d-block"> <%# d-block для отображения %>
              <%= @item.errors.full_messages_for(:price).join(', ') %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-3"> <%# col-md-2 для service_fee %>
        <div class="mb-3">
          <%= form.label :service_fee, class: 'form-label' %>
          <%= form.text_field :service_fee, class: 'form-control' %>
          <% if @item.errors[:service_fee].any? %>
            <div class="invalid-feedback d-block"> <%# d-block для отображения %>
              <%= @item.errors.full_messages_for(:service_fee).join(', ') %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-3"> <%# col-md-3 для delivery_in_Japan (если хотите его тоже чуть длиннее) %>
        <div class="mb-3">
          <%= form.label :internal_shipping_costs, class: 'form-label' %>
          <%= form.text_field :internal_shipping_costs, class: 'form-control' %>
          <% if @item.errors[:internal_shipping_costs].any? %>
            <div class="invalid-feedback d-block"> <%# d-block для отображения %>
              <%= @item.errors.full_messages_for(:internal_shipping_costs).join(', ') %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-3"> <%# col-md-2 для country_fee %>
        <div class="mb-3">
          <%= form.label :country_fee, class: 'form-label' %>
          <%= form.text_field :country_fee, class: 'form-control' %>
          <% if @item.errors[:country_fee].any? %>
            <div class="invalid-feedback d-block"> <%# d-block для отображения %>
              <%= @item.errors.full_messages_for(:country_fee).join(', ') %>
            </div>
          <% end %>
        </div>
      </div>
    </div> <%# Конец .row %>

    <div class="mb-3">
      <%= form.submit 'Сохранить', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;" data-bs-theme="light">
	<div class="container-fluid">
		<a class="navbar-brand" href="<%= root_path %>">Navbar</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="<%= items_path %>">Items</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="<%= packages_path %>">Packages</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="<%= customers_path %>">Customers</a>
				</li>
			</ul>
			<form class="d-flex" role="search">
				<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
				<button class="btn btn-outline-success" type="submit">Search</button>
			</form>
		</div>
	</div>
</nav>

app/views/shared/flash/_danger.html.erb
<div class="alert alert-danger flash-message show" role="alert">
	<%= alert %>
	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	<div class="progress-bar-container">
		<div class="progress-bar"></div>
	</div>
</div>

app/views/shared/flash/_success.html.erb
<div class="alert alert-success flash-message show" role="alert">
	<%= notice %>
	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	<div class="progress-bar-container">
		<div class="progress-bar"></div>
	</div>
</div>